### ISSUE TITLE
Error running the code "bash scripts/dense_cap_train.sh [dataset] [net] [ckpt_to_init] [data_dir] [step]" trainning model.

### ISSUE THREAD

**Issue by liuxx2016** [InnerPeace-Wu/densecap-tensorflow#11]
Loaded.
Fix Resnet V1 layers..
Fixed.
Ckpt path: ckpt/./res50_densecap_iter_500000.ckpt
Found pickle file, restore training process.
Last snapshot iters:100000
Traceback (most recent call last):
  File "./tools/train_net.py", line 214, in <module>
    main()
  File "./tools/train_net.py", line 210, in main
    max_iters=args.max_iters)
  File "/home/liuxiaoxiao/docment/tools/../lib/dense_cap/train.py", line 485, in train_net
    sw.train_model(sess, max_iters)
File "/home/liuxiaoxiao/docment/tools/../lib/dense_cap/train.py", line 356, in train_model
    blobs = self.data_layer.forward()
  File "/home/liuxiaoxiao/docment/tools/../lib/fast_rcnn/layer.py", line 99, in forward
    blobs = self._get_next_minibatch()
  File "/home/liuxiaoxiao/docment/tools/../lib/fast_rcnn/layer.py", line 95, in _get_next_minibatch
    return get_minibatch(minibatch_db)
File "/home/liuxiaoxiao/docment/tools/../lib/fast_rcnn/minibatch.py", line 41, in get_minibatch
    im_blob, im_scales, roidb = _get_image_blob(roidb, random_scale_inds)
  File "/home/liuxiaoxiao/docment/tools/../lib/fast_rcnn/minibatch.py", line 101, in _get_image_blob
    cfg.TRAIN.MAX_SIZE)
  File "/home/liuxiaoxiao/docment/tools/../lib/utils/blob.py", line 37, in prep_im_for_blob
    im = im.astype(np.float32, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by InnerPeace-Wu** [comment]
Hi,
Please refer to the [issue](https://github.com/InnerPeace-Wu/densecap-tensorflow/issues/12#issuecomment-379552424).

**Comment by liuxx2016** [comment]
Thank you very much, the problem was solved._
