### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/home/yanghui/densecap-tensorflow/VG/1.2/train_gt_regions/2375025.json'

### ISSUE THREAD

**Issue by huiyang865** [InnerPeace-Wu/densecap-tensorflow#17]
Ｈｉ,

After the preparing data process, I train the model with the command:
"bash scripts/dense_cap_train.sh [dataset] [net] [ckpt_to_init] [data_dir] [step]"

An error appears:
Traceback (most recent call last):
  File "/data/yanghui/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/data/yanghui/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/data/yanghui/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/yanghui/densecap-tensorflow/tools/train_net.py", line 214, in <module>
    main()
  File "/home/yanghui/densecap-tensorflow/tools/train_net.py", line 168, in main
    imdb, roidb = get_roidb_limit_ram(args.imdb_name)
  File "/home/yanghui/densecap-tensorflow/tools/train_net.py", line 123, in get_roidb_limit_ram
    roidb = imdb.roidb
  File "/home/yanghui/densecap-tensorflow/lib/datasets/imdb.py", line 82, in roidb
    self._roidb = self.roidb_handler()
  File "/home/yanghui/densecap-tensorflow/lib/datasets/visual_genome.py", line 144, in gt_roidb
    gt_roidb = self.gt_roidb_limit_ram()
  File "/home/yanghui/densecap-tensorflow/lib/datasets/visual_genome.py", line 196, in gt_roidb_limit_ram
    dictionary = self._load_vg_annotation(idx)
  File "/home/yanghui/densecap-tensorflow/lib/datasets/visual_genome.py", line 273, in _load_vg_annotation
    with open(self.region_imset_path + '/%s.json' % index, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/yanghui/densecap-tensorflow/VG/1.2/train_gt_regions/2375025.json'

I check the directory of '/home/yanghui/densecap-tensorflow/VG/1.2/', there is no folder 'train_gt_regions'. How does this folder generate?

**Comment by huiyang865** [comment]
I have lost the --limit_ram parameters while run the 'python preprocess.py' command.

**Comment by thirdeyetunnu** [comment]
Hi, I am getting the same error and i am using uplimit RAM version.
please help...

**Comment by heartraeh** [comment]
I am getting the same error
